#!/bin/bash -e

# Requirements:
# - fzf
# - aws cli

function get_cache() {
    aws s3 cp --quiet s3://ec2-cache.nsofnetworks/instances.fzf >(cat)
}

chosen=$(get_cache | fzf)

export key=$(echo $chosen | rev | cut -d ' ' -f1 | rev)
export ip=$(echo $chosen | rev | cut -d ' ' -f2 | rev)

ssh -i ~/.ssh/$key.pem ubuntu@$ip
